import type { AppRole } from './roleMap';

export const PERMISSIONS = {
  VIEW_EXECUTIVE_DASHBOARD: 'VIEW_EXECUTIVE_DASHBOARD',
  VIEW_QUALITY_DASHBOARD: 'VIEW_QUALITY_DASHBOARD',
  VIEW_SALES_FUNNEL: 'VIEW_SALES_FUNNEL',
  VIEW_RISK_QUEUE: 'VIEW_RISK_QUEUE',
  VIEW_TNI_HEATMAP: 'VIEW_TNI_HEATMAP',
  VIEW_ANALYST_PERFORMANCE: 'VIEW_ANALYST_PERFORMANCE',
  VIEW_EVIDENCE: 'VIEW_EVIDENCE',
  VIEW_SETTINGS: 'VIEW_SETTINGS',
  VIEW_ADMIN_PANEL: 'VIEW_ADMIN_PANEL',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLE_ACCESS: 'MANAGE_ROLE_ACCESS',
  EXPORT_REPORTS: 'EXPORT_REPORTS',
  VIEW_BRANCH_LEVEL: 'VIEW_BRANCH_LEVEL',
  VIEW_PROCESS_LEVEL: 'VIEW_PROCESS_LEVEL',
  VIEW_TEAM_LEVEL: 'VIEW_TEAM_LEVEL',
  VIEW_SELF_ONLY: 'VIEW_SELF_ONLY',
  VIEW_PAYROLL_ADMIN: 'VIEW_PAYROLL_ADMIN',
  VIEW_HR_ADMIN: 'VIEW_HR_ADMIN',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

const allDashboards: Permission[] = [
  PERMISSIONS.VIEW_EXECUTIVE_DASHBOARD,
  PERMISSIONS.VIEW_QUALITY_DASHBOARD,
  PERMISSIONS.VIEW_SALES_FUNNEL,
  PERMISSIONS.VIEW_RISK_QUEUE,
  PERMISSIONS.VIEW_TNI_HEATMAP,
  PERMISSIONS.VIEW_ANALYST_PERFORMANCE,
  PERMISSIONS.VIEW_EVIDENCE,
  PERMISSIONS.VIEW_SETTINGS,
  PERMISSIONS.EXPORT_REPORTS,
];

export const ROLE_PERMISSIONS: Record<AppRole, Permission[]> = {
  SUPER_ADMIN: [
    ...allDashboards,
    PERMISSIONS.VIEW_ADMIN_PANEL,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ROLE_ACCESS,
    PERMISSIONS.VIEW_BRANCH_LEVEL,
    PERMISSIONS.VIEW_PROCESS_LEVEL,
    PERMISSIONS.VIEW_TEAM_LEVEL,
    PERMISSIONS.VIEW_HR_ADMIN,
    PERMISSIONS.VIEW_PAYROLL_ADMIN,
  ],
  CEO: [
    PERMISSIONS.VIEW_EXECUTIVE_DASHBOARD,
    PERMISSIONS.VIEW_QUALITY_DASHBOARD,
    PERMISSIONS.VIEW_SALES_FUNNEL,
    PERMISSIONS.VIEW_RISK_QUEUE,
    PERMISSIONS.VIEW_ANALYST_PERFORMANCE,
    PERMISSIONS.VIEW_BRANCH_LEVEL,
    PERMISSIONS.VIEW_PROCESS_LEVEL,
  ],
  HO_QA: [
    PERMISSIONS.VIEW_QUALITY_DASHBOARD,
    PERMISSIONS.VIEW_RISK_QUEUE,
    PERMISSIONS.VIEW_TNI_HEATMAP,
    PERMISSIONS.VIEW_ANALYST_PERFORMANCE,
    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_BRANCH_LEVEL,
    PERMISSIONS.VIEW_PROCESS_LEVEL,
    PERMISSIONS.VIEW_TEAM_LEVEL,
    PERMISSIONS.EXPORT_REPORTS,
  ],
  HO_OPERATIONS: [
    PERMISSIONS.VIEW_EXECUTIVE_DASHBOARD,
    PERMISSIONS.VIEW_SALES_FUNNEL,
    PERMISSIONS.VIEW_RISK_QUEUE,
    PERMISSIONS.VIEW_ANALYST_PERFORMANCE,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_BRANCH_LEVEL,
    PERMISSIONS.VIEW_PROCESS_LEVEL,
    PERMISSIONS.EXPORT_REPORTS,
  ],
  QUALITY_MANAGER: [
    PERMISSIONS.VIEW_QUALITY_DASHBOARD,
    PERMISSIONS.VIEW_TNI_HEATMAP,
    PERMISSIONS.VIEW_ANALYST_PERFORMANCE,
    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_PROCESS_LEVEL,
    PERMISSIONS.VIEW_TEAM_LEVEL,
  ],
  OPERATIONS_MANAGER: [
    PERMISSIONS.VIEW_EXECUTIVE_DASHBOARD,
    PERMISSIONS.VIEW_SALES_FUNNEL,
    PERMISSIONS.VIEW_RISK_QUEUE,
    PERMISSIONS.VIEW_ANALYST_PERFORMANCE,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_PROCESS_LEVEL,
    PERMISSIONS.VIEW_BRANCH_LEVEL,
  ],
  PROCESS_MANAGER: [
    PERMISSIONS.VIEW_EXECUTIVE_DASHBOARD,
    PERMISSIONS.VIEW_QUALITY_DASHBOARD,
    PERMISSIONS.VIEW_SALES_FUNNEL,
    PERMISSIONS.VIEW_ANALYST_PERFORMANCE,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_PROCESS_LEVEL,
  ],
  BRANCH_MANAGER: [
    PERMISSIONS.VIEW_EXECUTIVE_DASHBOARD,
    PERMISSIONS.VIEW_QUALITY_DASHBOARD,
    PERMISSIONS.VIEW_ANALYST_PERFORMANCE,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_BRANCH_LEVEL,
  ],
  TEAM_LEADER: [
    PERMISSIONS.VIEW_ANALYST_PERFORMANCE,
    PERMISSIONS.VIEW_TNI_HEATMAP,
    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_TEAM_LEVEL,
  ],
  QUALITY_ANALYST: [
    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.VIEW_QUALITY_DASHBOARD,
    PERMISSIONS.VIEW_SETTINGS,
  ],
  TRAINER: [
    PERMISSIONS.VIEW_TNI_HEATMAP,
    PERMISSIONS.VIEW_ANALYST_PERFORMANCE,
    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.VIEW_SETTINGS,
  ],
  HR_ADMIN: [
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_HR_ADMIN,
  ],
  PAYROLL_ADMIN: [
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_PAYROLL_ADMIN,
  ],
  ANALYST: [
    PERMISSIONS.VIEW_ANALYST_PERFORMANCE,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_SELF_ONLY,
  ],
  VIEWER: [
    PERMISSIONS.VIEW_EXECUTIVE_DASHBOARD,
    PERMISSIONS.VIEW_QUALITY_DASHBOARD,
    PERMISSIONS.VIEW_SALES_FUNNEL,
    PERMISSIONS.VIEW_RISK_QUEUE,
    PERMISSIONS.VIEW_SETTINGS,
  ],
};

export const ROUTE_PERMISSIONS: Record<string, Permission> = {
  '/command-center': PERMISSIONS.VIEW_EXECUTIVE_DASHBOARD,
  '/quality': PERMISSIONS.VIEW_QUALITY_DASHBOARD,
  '/sales-funnel': PERMISSIONS.VIEW_SALES_FUNNEL,
  '/risk': PERMISSIONS.VIEW_RISK_QUEUE,
  '/tni': PERMISSIONS.VIEW_TNI_HEATMAP,
  '/analysts': PERMISSIONS.VIEW_ANALYST_PERFORMANCE,
  '/evidence': PERMISSIONS.VIEW_EVIDENCE,
  '/settings': PERMISSIONS.VIEW_SETTINGS,
  '/admin': PERMISSIONS.VIEW_ADMIN_PANEL,
  '/profile': PERMISSIONS.VIEW_SETTINGS,
};

export function hasPermission(role: AppRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function getPermissions(role: AppRole): Permission[] {
  return ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS.VIEWER;
}
